"""conversation state

Revision ID: 3e9539fd4579
Revises: 108f0dd0d579
Create Date: 2026-08-14 19:56:33.177075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3e9539fd4579'
down_revision: Union[str, Sequence[str], None] = '108f0dd0d579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# El tipo ENUM 'lead_stage' ya existe (creado por la migracion 108f0dd0d579
# para leads.stage). ConversationState.current_state reutiliza el mismo tipo
# (SPEC.md seccion 2: un unico state machine de 10 estados). Se usa
# postgresql.ENUM (no sa.Enum generico) con create_type=False porque
# create_type solo se respeta en el tipo nativo del dialecto — sa.Enum
# generico lo ignora al adaptarse al ENUM nativo de Postgres.
lead_stage_enum = postgresql.ENUM(
    'NEW', 'DISCOVERING', 'QUALIFYING', 'PROPERTY_SEARCH', 'PRESENTING',
    'SCHEDULING', 'BOOKED', 'HANDOFF', 'NURTURE', 'LOST',
    name='lead_stage', create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('current_state', lead_stage_enum, nullable=False),
    sa.Column('last_transition_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empty_search_count', sa.SmallInteger(), nullable=False),
    sa.Column('no_response_count', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
