"""property y human_handoff

Revision ID: a527a85a6c88
Revises: 3e9539fd4579
Create Date: 2026-08-14 21:44:08.625525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a527a85a6c88"
down_revision: Union[str, Sequence[str], None] = "3e9539fd4579"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# El tipo ENUM 'lead_purpose' ya existe (creado por la migracion 108f0dd0d579
# para leads.purpose). Property.purpose reutiliza el mismo tipo (SPEC.md
# seccion 5: mismo dominio residential|investment del contrato de extraccion
# del LLM). Se usa postgresql.ENUM (no sa.Enum generico) con
# create_type=False -- ver gotcha documentado para ConversationState.current_state
# reutilizando lead_stage: sa.Enum generico ignora create_type al adaptarse
# al tipo nativo de Postgres.
lead_purpose_enum = postgresql.ENUM(
    "RESIDENTIAL",
    "INVESTMENT",
    name="lead_purpose",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("property_type", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("neighborhood", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("bedrooms", sa.SmallInteger(), nullable=False),
        sa.Column("bathrooms", sa.SmallInteger(), nullable=True),
        sa.Column("area", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("purpose", lead_purpose_enum, nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "RESERVED", "SOLD", "RENTED", "INACTIVE", name="property_status"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("images", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("availability", sa.String(length=255), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "human_handoffs",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Enum("OPEN", "RESOLVED", name="handoff_status"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("human_handoffs")
    op.drop_table("properties")
    # ### end Alembic commands ###
    # drop_table no elimina los tipos ENUM propios de esta migracion.
    # 'lead_purpose' NO se dropea aqui: pertenece a la migracion
    # 108f0dd0d579 (leads.purpose) y sigue en uso por esa tabla.
    for enum_name in ("property_status", "handoff_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
